services:
  db:
    image: mysql:8.4
    restart: always
    container_name: db
    environment:
      MYSQL_DATABASE: ${DB_NAME:-db}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    volumes:
      - ./db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "-u$MYSQL_USER", "-p$MYSQL_PASSWORD",  "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  dip-bot:
    build: .
    depends_on:
      db:
        condition: service_healthy
    restart: always
    container_name: bot
    user: "${DIPBOT_UID:-1000}:${DIPBOT_GID:-1000}"
    env_file:
      - .env
    environment:
      DB_HOST: db
    volumes:
      - ./log:/app/log
      - ./images:/app/images:ro
      - ./var:/app/var
