---
version: "3.9"

services:
  db:
    image: mysql
    restart: always
    container_name: db
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./db:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "-u$MYSQL_USER", "-p$MYSQL_PASSWORD",  "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  dip-bot:
    build: .
    depends_on:
      db:
        condition: service_healthy
    restart: always
    container_name: bot
    volumes:
      - ./log:/log
      - ./guilds:/guilds
      - ./images:/images
      - ./reported_images:/reported_images
    network_mode: "host"
